contact_links:
  - name: Question 🙋
    url: https://github.com/fabston/little-snitch-blocklist/discussions/categories/general
    about: Ask your question in our Discussions Channel
  - name: False Positive 📛
    url: https://github.com/fabston/little-snitch-blocklist/discussions/categories/false-positive
    about: There is a domain that shouldn't be blocked
  - name: Domain addition 📝
    url: https://github.com/fabston/little-snitch-blocklist/discussions/categories/domain-addition
    about: There is a domain that should be blocked